version: "3.9"

services:
  chat_cra:
    build: ./app
    image: local/chat_cra
    container_name: chat_cra
    depends_on:
      - chat_server
      - mongo
      - redis
    restart: "no"
    ports:
      - 3001:443
    networks:
      - chat_network
  chat_server:
    build: .
    image: local/chat_server
    container_name: chat_server
    depends_on:
      - mongo
      - redis
    restart: "no"
    ports:
      - 3000:3000
    networks:
      - chat_network
  mongo:
    build: ./.docker/mongo
    image: local/mongo_single_rs
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pw2022mdb
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017
    command: mongod --keyFile /opt/keyfile --replSet myReplicaSet --bind_ip localhost,mongo
    networks:
      - chat_network
  redis:
    container_name: redis
    image: redis:7-bullseye
    command: redis-server --requirepass pw2022r
    restart: always
    ports:
      - 6379:6379
    networks:
      - chat_network
  swagger:
    container_name: swagger
    image: swaggerapi/swagger-editor:v4.4.2
    ports:
      - 80:8080
    restart: always
    networks:
      - chat_network
networks:
  chat_network:
